### ISSUE TITLE
Upgrade sudoku-go library to fix leftover problem

### ISSUE THREAD

**Issue by einsitang** [Alex-Merrill/sudoku-tui#18]
thanks for use einsitang/sudoku-go (old name is forfuns/sudoku-go) library
and I'am sorry that I have long time no continuing maintenance this repository 
just last week look out this repository and I found some bug because I’am not test enough,that is my fault

**level medium no work because change some parameter and skip testing**
*is fixed now*

**multiple solutions will happen in level hard and expert , some time medium too**
that is beacuse I generate random sudoku then dig hole to make puzzle , after puzzle done I will  use `sudoku.Sudoku` to solve twice and check equals answer . I shoud test more time then this problem  can't happen .
I fix this problem and make one-solution , but this generate algorithm maybe not good enough , take a long time, I  find another day to recode the generator , but generator problem also exist in other repository , they will take precedence

you can use new library and new function to test it

that is the new repository https://github.com/einsitang/sudoku-go because I change username

in the end , my english not good , so hope you can make sense of me

**Comment by einsitang** [comment]
the sudoku generator and solver both recode, more test case with benchmark , they all seem to work very well

**Comment by Alex-Merrill** [comment]
@einsitang Thank you for checking this out! I appreciate your help here and no problem about the issues, I worked around them :). 

Thanks for fixing the level medium puzzles not working bug, there was definitely a steep difficulty jump from the easy to medium levels I had set since I was just skipping to hard.

I haven't done too much research into it, but from what I understand, generating guaranteed one-solution puzzles is not a trivial task, so no worries about that. If I wanted something perfect I would probably have to go read some research papers on this and implement the algorithm myself as I didn't find a great one from the cursory search I did when I originally created this.
